baseURL = "https://fernandosoliva.com"
languageCode = "pt-br"
title = "Fernando Soliva"
theme = "hugo-cactus-theme"

[params]
	name = "Fernando Soliva"
	description = ""
	bio = "Software Developer - Go - K8S - Serverless"
	# Enter optionally your twitter account
	twitter = "fernandosolivas"
	enableRSS = true

	# Integrate Javascript files or stylesheets by adding the url to the external assets or by
	# linking local files with their path relative to the static folder, e.g. "css/styles.css"
	customCSS = []
	customJS  = []

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = ""
	subscribe = ""
	# Pagination links
	olderPosts = ""
	newerPosts = ""
	readMore = ""
	copyright = ""
	# Sharing options and author information in posts
	aboutAuthor = "Fernando Soliva - Desenvolvedor de Software"
	tweet = ""
	share = ""
	# 404 page
	title404 = "Pagina não encontrada"
	subtitle404 = "Oops! Parece deixei essa página fora e talvez não tenha visto, me avisa? Meu e-mail é: me@fernandosoliva.com"

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "font-awesome"
    # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
    socialIconStyle = "circle"

# Add additional social link entries underneath
[social]
    twitter  = "https://www.twitter.com/fernandosolivas"
    github   = "https://www.github.com/fernandosolivas"
	linkedin = "https://www.linkedin.com/in/fernandosoliva/"
	medium = "https://dev.to/fernandosolivas"
